version: "3"

networks:
  lcmap:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.32.0/24

services:
  zookeeper:
    image: zookeeper:3.4.9
    restart: always
    ports:
      - "2181:2181"
    networks:
      - lcmap
  mesos-master:
    image: mesosphere/mesos-master:1.0.3-rc2
    ports:
      - "5050:5050"
    networks:
      - lcmap
    links:
      - zookeeper
    depends_on:
      - zookeeper
    environment:
      - MESOS_PORT=5050
      - MESOS_ZK=zk://zookeeper:2181/mesos
      - MESOS_QUORUM=1
      - MESOS_REGISTRY=in_memory
      - MESOS_LOG_DIR=/var/log/mesos
      - MESOS_WORK_DIR=/var/tmp/mesos
    volumes:
      - .tmp/volumes/log/mesos:/var/log/mesos
      - .tmp/volumes/tmp/mesos:/var/tmp/mesos
  mesos-slave:
    image: mesosphere/mesos-slave:1.0.3-rc2
    networks:
      - lcmap
    depends_on:
      - zookeeper
      - mesos-master
    links:
      - zookeeper
    privileged: true
    restart: always
    environment:
      - MESOS_PORT=5051
      - MESOS_MASTER=zk://zookeeper:2181/mesos
      - MESOS_SWITCH_USER=0
      - MESOS_CONTAINERIZERS=mesos,docker
      - MESOS_LOG_DIR=/var/log/mesos
      - MESOS_WORK_DIR=/var/tmp/mesos
    volumes:
      - /usr/bin/docker:/usr/local/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/sys/fs/cgroup
  marathon:
    image: mesoscloud/marathon:1.1.1
    ports:
      - "8080:8080"
    networks:
      - lcmap
    restart: always
    depends_on:
      - zookeeper
      - mesos-master
      - mesos-slave
    environment:
      - MARATHON_HOSTNAME=marathon
      - MARATHON_HTTPS_ADDRESS=marathon
      - MARATHON_HTTP_ADDRESS=marathon
      - MARATHON_MASTER=zk://zookeeper:2181/mesos
      - MARATHON_ZK=zk://zookeeper:2181/marathon
  rabbitmq:
    image: rabbitmq:3.6.6-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - lcmap
    volumes:
      - ./volumes/rabbitmq/var:/var/lib/rabbitmq
  cassandra:
    image: cassandra:3.9
    ports:
      - "9042:9042"
    networks:
      - lcmap
    volumes:
      - ./volumes/cassandra/var:/var/lib/cassandra
  elasticsearch:
    image: elasticsearch:5.2.0
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - lcmap
    volumes:
      - ./volumes/elasticsearch/data:/usr/share/elasticsearch/data
