version: "3"

networks:
  lcmap:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.32.0/24

services:
  zookeeper:
    image: zookeeper:3.4.9
    restart: always
    ports:
      - "2181:2181"
    networks:
      - lcmap

  mesos-dns:
    image: tobilg/mesos-dns:v0.5.2
    ports:
      - "5353:53"
      - "8123:8123"
    networks:
      lcmap:
        ipv4_address: 192.168.32.53
    links:
      - zookeeper
    depends_on:
      - zookeeper
    environment:
      - MESOS_ZK=zk://zookeeper:2181/mesos
      - LOCAL_IP=192.168.32.53
      - MESOS_DNS_EXTERNAL_SERVERS=8.8.8.8,8.8.4.4
      - MESOS_DNS_HTTP_ENABLED=true
      - MESOS_DNS_HTTP_PORT=8123

  mesos-master:
    image: mesosphere/mesos-master:1.0.3-rc2
    hostname: ${HOSTNAME:-localhost}
    ports:
      - "5050:5050"
    networks:
      - lcmap
    links:
      - zookeeper
    depends_on:
      - zookeeper
    environment:
      - MESOS_PORT=5050
      - MESOS_ZK=zk://zookeeper:2181/mesos
      - MESOS_QUORUM=1
      - MESOS_REGISTRY=in_memory
      - MESOS_LOG_DIR=/var/log/mesos
      - MESOS_WORK_DIR=/var/tmp/mesos
    volumes:
      - ./volumes/mesos/log:/var/log/mesos
      - ./volumes/mesos/tmp:/var/tmp/mesos

  mesos-slave:
    image: mesosphere/mesos-slave:1.0.3-rc2
    networks:
      - lcmap
    hostname: ${HOSTNAME:-localhost}
    ports:
      - "5051:5051"
    dns:
      - 192.168.32.53
    depends_on:
      - zookeeper
      - mesos-master
      - mesos-dns
    links:
      - zookeeper
    privileged: true
    restart: always
    environment:
      - MESOS_PORT=5051
      - MESOS_MASTER=zk://zookeeper:2181/mesos
      - MESOS_SWITCH_USER=0
      - MESOS_CONTAINERIZERS=mesos,docker
      - MESOS_LOG_DIR=/var/log/mesos
      - MESOS_WORK_DIR=/var/tmp/mesos
    volumes:
      - ./volumes/mesos/log:/var/log/mesos
      - ./volumes/mesos/tmp:/var/tmp/mesos
      - /usr/bin/docker:/usr/local/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/sys/fs/cgroup

  marathon:
    image: mesoscloud/marathon:1.1.1
    ports:
      - "8080:8080"
    networks:
      - lcmap
    restart: always
    depends_on:
      - zookeeper
      - mesos-master
      - mesos-slave
    environment:
      - MARATHON_HOSTNAME=${HOSTNAME:-localhost}
      - MARATHON_HTTPS_ADDRESS=marathon
      - MARATHON_HTTP_ADDRESS=marathon
      - MARATHON_MASTER=zk://zookeeper:2181/mesos
      - MARATHON_ZK=zk://zookeeper:2181/marathon

  mesos-spark-cluster-dispatcher:
    image: usgseros/mesos-spark:1.1.1-2.1.0
    ports:
      - "7077:7077"
      - "8081:8081"
    networks:
      - lcmap
    links:
      - zookeeper
      - mesos-master
    depends_on:
      - zookeeper
      - mesos-master
    environment:
      - MESOS_MASTER=mesos://mesos-master:5050
      - ZOOKEEPER=zookeeper:2181
      - FRAMEWORK_NAME=LCMAPServicesSparkCluster

  rabbitmq:
    image: rabbitmq:3.6.6-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - lcmap
    volumes:
      - ./volumes/rabbitmq/var:/var/lib/rabbitmq

  cassandra:
    image: cassandra:3.9
    ports:
      - "9042:9042"
    networks:
      - lcmap
    volumes:
      - ./volumes/cassandra/var:/var/lib/cassandra

  elasticsearch:
    image: elasticsearch:5.2.0
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - lcmap
    volumes:
      - ./volumes/elasticsearch/data:/usr/share/elasticsearch/data

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
      - "6667:6667"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=${HOSTNAME}
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    networks:
      - lcmap
    depends_on:
      - zookeeper
    links:
      - zookeeper
    volumes:
      - ./volumes/kafka/data:/usr/share/elasticsearch/data
